bundler_args: --without development --path vendor/bundle
script:
  - bundle exec rake travis:setup
  - bundle exec rake db:reset db:setup db:migrate db:test:prepare
  - bundle exec rake spec
language: ruby
before_install:
  - gem install bundler
  - mysql -e 'create database hyperion_test'
rvm:
  - 1.9.3
