language: ruby

rvm:
  - 1.9.3
  - 2.0.0

bundler_args: --without development:production

before_install:
  - gem update bundler

script:
  - bundle exec rake setup db:create db:migrate spec

matrix:
  allow_failures:
    - rvm: 2.0.0
