development:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: hyperion_development
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: hyperion_test
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: hyperion
  host: localhost
